export enum AuditAction {
  USER_REGISTERED = 'USER_REGISTERED',
  INVITATION_SENT = 'INVITATION_SENT',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  EMAIL_QUEUED = 'EMAIL_QUEUED',
  EMAIL_SENT = 'EMAIL_SENT',
  EMAIL_FAILED = 'EMAIL_FAILED',
}
