export enum AuditAction {
  USER_REGISTERED = 'USER_REGISTERED',
  INVITATION_SENT = 'INVITATION_SENT',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  INVITATION_REVOKED = 'INVITATION_REVOKED',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  LOGIN_OTP_REQUESTED = 'LOGIN_OTP_REQUESTED',
  LOGIN_OTP_USED = 'LOGIN_OTP_USED',
  EMAIL_QUEUED = 'EMAIL_QUEUED',
  EMAIL_SENT = 'EMAIL_SENT',
  EMAIL_FAILED = 'EMAIL_FAILED',
}
